### PR TITLE
Remove duplicate apple-touch-icon.png

### PR DESCRIPTION
**Pull request by zdroid**
It is not referenced anywhere, so that's not an issue.

Related: should `favicon.ico` also be part of the `assets/img/favicons/` directory?

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
This icon was indeed not removed in this commit:
https://github.com/twbs/blog/commit/1f66e6716e4fcf77ad276582b0f300fb5f519745

It's better to leave `favicon.ico` in the root, browsers load it when an image or pdf is opened. You can check this in your devtools with for example this image:

https://getbootstrap.com/docs/4.4/assets/img/bootstrap-themes@2x.png

**Comment by XhmikosR** [comment]
This isn't duplicate, it was done on purpose. I'll revert this

**Comment by zdroid** [comment]
What's the purpose of it then?

**Comment by XhmikosR** [comment]
Because many browsers and tools use it and it doesn't cost us anything to have it. If we ever move to Hugo, we'll be able to remove it then.

**Comment by zdroid** [comment]
This line in [`favicons.html`](https://github.com/twbs/blog/blob/gh-pages/_includes/favicons.html):
```html
<link rel="apple-touch-icon" href="/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
```

It says `apple-touch-icon` is loaded from that location, not `/`. Thus there are two icons for no reason. One of them could be removed to serve both functions.

**Comment by XhmikosR** [comment]
Like I said, I'd rather keep it as is.

**Comment by zdroid** [comment]
We have `favicon.ico` only once, but `apple-touch-icon.png` twice. What's the difference?

**Comment by XhmikosR** [comment]
No difference, I just decided when I added the favicons to not duplicate favicon.ico. It could be either way.

Just let it be. It's a trivial thing and we all have more important things to do.

**Comment by zdroid** [comment]
I thought it was something browser-related, but thanks for explaining anyway. Sorry if it was tiresome. :p

**Pull request merged**
