### PR TITLE
Add markdownlint

### PR DESCRIPTION
**Pull request by XhmikosR**
Not sure if we want this, I personally think it's useful to keep things consistent.

Some of the current changes I will split them and merge them manually to gh-pages since they are unrelated.

We should add Travis CI to the repo if we go ahead with this.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@mdo can you enable Travis CI for this repo? And protect the gh-pages branch to make sure CI passes and the branch is up to date?

I went with the Ruby solution so that we don't introduce another dep (Node.js).

**Comment by XhmikosR** [comment]
I'm gonna split the html-proofer addition and add GH Actions in another PR.

The current markdownlint gem conflicts with jekyll's 4.0.0 requirements.

**Comment by XhmikosR** [comment]
@mdo: ping? We could lax the config if needed but I still believe it's good to have it :)

**Comment by mdo** [comment]
Do we have this on the main repo? Could be nice everywhere we write Markdown.

**Comment by XhmikosR** [comment]
> Do we have this on the main repo? Could be nice everywhere we write Markdown.

We don't but I can try adding a similar solution which is using markdownlint and not the Rubygem.

**Pull request merged**
