### PR TITLE
Move `bootstrap-icons-1-11-0.md` into 2023 dir

### PR DESCRIPTION
**Pull request by julien-deramond**
### Description

https://blog.getbootstrap.com/2022/11/11/bootstrap-icons-1-10-0/ is not the right URL since it was posted in 2023. Moreover, the blog post date was `November 11, 2022`.

### Live preview

- https://deploy-preview-400--bootstrapblog.netlify.app/
- https://deploy-preview-400--bootstrapblog.netlify.app/2023/09/12/bootstrap-icons-1-11-0/

### CODE REVIEW

**Comment by julien-deramond** [comment]
Closing it since already patched via https://github.com/twbs/blog/commit/ae026e50e6d2d2c87f9008abbab7d5891a5f3a87

**Comment by mdo** [comment]
> Note: the alias doesn't work

😲

**Comment by mdo** [comment]
https://blog.getbootstrap.com/2022/09/12/bootstrap-icons-1-11-0/ redirects to https://blog.getbootstrap.com/2023/09/12/bootstrap-icons-1-11-0/ for me...

**Comment by julien-deramond** [comment]
Oh it was probably a cache issue since the first time I tried it, the redirection didn't work. Perfect 👌

**Pull request closed without merging**
