### PR TITLE
Move 2012-2019 posts to subfolders

### PR DESCRIPTION
**Pull request by mdo**
Organizes the `_posts` folder better.

/cc @XhmikosR

### CODE REVIEW

**Comment by XhmikosR** [comment]
I need to check closer, I'll get back to you later or tomorrow 🙂

**Comment by XhmikosR** [comment]
Actually this breaks all links. https://github.com/twbs/blog/pull/144/checks?check_run_id=693688011#step:11:13

Weird that Jekyll doesn't fail the build in this case...

I'll see if I can fix it.

**Comment by XhmikosR** [comment]
At this point I'd say let's leave it as is. We need to move with Jekyll 4.x and #137 anyway.

**Comment by mdo** [comment]
> Actually this breaks all links.

Not all the links, just ones using `post_url`, which have been fixed in da98730 by updating the path to those files.

**Comment by XhmikosR** [comment]
@mdo this doesn't feel right to me. You are using folders for years, yet the post filenames have also the year.

I'd drop this patch for now.

**Comment by XhmikosR** [comment]
Also, it seems you removed a post.

I'd say put this on hold until I have time to look into it. It doesn't really gain us anything in the sense that if I want the latest post, I just scroll down the folder.

**Comment by mdo** [comment]
Superseded by #180.

**Pull request closed without merging**
